#!/bin/sh
# Regenerates src/embedded_stdlib_registry.bl from lib/std/*.bl and lib/pkg/*.bl.
# Run via `task gen-stdlib-registry`. CI fails if output differs from committed file.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/embedded_stdlib_registry.bl"

cd "$ROOT"

FILES=$(find lib/std lib/pkg -mindepth 1 -maxdepth 1 -name '*.bl' | LC_ALL=C sort)

for f in $FILES; do
    base=$(basename "$f" .bl)
    case "$base" in
        [a-zA-Z_]*) ;;
        *) echo "gen_embedded_stdlib: invalid identifier in '$f'" >&2; exit 1 ;;
    esac
    case "$base" in
        *[!a-zA-Z0-9_]*) echo "gen_embedded_stdlib: invalid identifier in '$f'" >&2; exit 1 ;;
    esac
done

TMP="$OUT.tmp.$$"
trap 'rm -f "$TMP"' EXIT

{
    echo "// AUTO-GENERATED by scripts/gen_embedded_stdlib.sh — DO NOT EDIT."
    echo "// Run \`task gen-stdlib-registry\` after adding lib/std or lib/pkg files."
    echo ""
    echo "import compiler.{embedded_stdlib}"
    echo ""
    for f in $FILES; do
        ns=${f#lib/}; ns=${ns%%/*}
        base=$(basename "$f" .bl)
        echo "const embedded_${ns}_${base}: Str = #embed(\"../$f\")"
    done
    echo ""
    echo "pub fn init_embedded_stdlib() {"
    for f in $FILES; do
        ns=${f#lib/}; ns=${ns%%/*}
        base=$(basename "$f" .bl)
        if [ "$ns" = "pkg" ]; then key="pkg_${base}"; else key="${base}"; fi
        echo "    embedded_stdlib.insert(\"${key}\", embedded_${ns}_${base})"
    done
    echo "}"
} > "$TMP"

# Atomic, mtime-stable write: don't touch OUT if content is identical
# (avoids invalidating task's sources/generates tracking on no-op runs).
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    rm -f "$TMP"
    echo "unchanged $OUT"
else
    mv "$TMP" "$OUT"
    echo "wrote $OUT"
fi
